### ISSUE TITLE
Facing WindowsError: [Error 32] error while running sd.sd.convert_tree

### ISSUE THREAD

**Issue by ankurgulati** [BLLIP/bllip-parser#51] opened 2016-10-07 10:38 UTC
The error looks like this : 
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\nasdnjdn\\appdata\\local\\temp\\tmp6xftke'

Please help with a fix

**Comment by dmcc** [comment] 2016-10-07 14:37
If you're calling StanfordDependencies, I'm guessing it's related to https://github.com/dmcc/PyStanfordDependencies/issues/15. AFAICT, the issue isn't entirely solved, but there is a workaround.

**Comment by ankurgulati** [comment] 2016-10-07 14:43
@dmcc Can you help me with the workaround?

**Comment by dmcc** [comment] 2016-10-07 14:47
The workaround is:

> you might want to try replacing the `os.remove(input_file.name)` line (SubprocessBackend.py, line 80) with `pass`.

Looks like it's now line 87.

**Comment by dmcc** [comment] 2016-10-08 15:15
Closing this bug since it's really an issue in PySD. Please follow up on https://github.com/dmcc/PyStanfordDependencies/issues/15 if you're still having this problem.

**Closed by dmcc** 2016-10-08 15:15 UTC
