### ISSUE TITLE
Will not compile on windows

### ISSUE THREAD

**Issue by keilanderatsorensondotcom** [BLLIP/bllip-parser#55] opened 2017-03-13 18:22 UTC
It looks like the installer is not properly compiling bllipparser on windows.

Specs:
win7 64
python 2.7
latest VCForPython27.msi (as of 03/13/2017)

Console:
```
> pip install bllipparser
Collecting bllipparser
  Using cached bllipparser-2016.9.11.tar.gz
Requirement already satisfied: six in c:\python27\lib\site-packages (from bllipparser)
Installing collected packages: bllipparser
  Running setup.py install for bllipparser ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\me\\appdata\\local\\temp\\pip-build-olmpji\\bllipparser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\me\appdata\local\temp\pip-ftrhgb-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\CharniakParser.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\JohnsonReranker.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\ModelFetcher.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\ParsingShell.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\RerankerFeatureCorpus.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\RerankingParser.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\Utility.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\__init__.py -> build\lib.win-amd64-2.7\bllipparser
    copying python\bllipparser\__main__.py -> build\lib.win-amd64-2.7\bllipparser
    running build_ext
    building 'bllipparser._CharniakParser' extension
    error: Don't know how to compile first-stage/PARSE/swig/wrapper.C

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\me\\appdata\\local\\temp\\pip-build-olmpji\\bllipparser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\me\appdata\local\temp\pip-ftrhgb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\me\appdata\local\temp\pip-build-olmpji\bllipparser\
```

**Comment by dmcc** [comment] 2017-03-13 18:27
Thanks for the report! I think this is a duplicate of #48 (though I'm afraid that this issue was never completely resolved...). Unfortunately, I don't have access to a Windows developer environment, but I welcome any pull requests that address this issue.

**Closed by dmcc** 2017-03-13 18:27 UTC
